---
# Manage Advanced Package Manager configuration.
apt__enabled: True

# Install the upstream version of Docker.
docker_server__upstream: True

# Lists of FQDN hostnames which should be added to systemwide.
sshd__known_hosts:
  - github.com

# Manage unattended package upgrades.
unattended_upgrades__enabled: True

# Enables debops.users to manage user accounts.
users__enabled: True

# Manage the kernel configuration.
sysctl__enabled: False

# List of UNIX system user accounts to manage.
system_users__accounts:

  - name: 'ansible'
    # sshkeys:
    # - 'ssh-ed25519 ...'

# Ansible manage system user accounts.
system_users__enabled: False
