---
ansible_ssh_key: ''
# Manage Advanced Package Manager configuration.
apt__enabled: true
apt__keys:
  - url: https://download.docker.com/linux/ubuntu/gpg
apt__packages:
  - binutils
  - docker-ce
  - git
  - net-tools
apt__repositories:
  - repo: >-
      deb https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable

docker_server__python__dependent_packages3:
  - python3-dev
  - python3-docker
  - python3-setuptools
  - python3-virtualenv

# Install the upstream version of Docker.
docker_server__upstream: true

# Config values.
fxcore_fxcored_config:
  app.toml:
    API.Enable: false
  config.toml:
    log_level: info
    #moniker: Foo

# List of fxcored keys.
fxcore_fxcored_keys: []

# Home path for config and data.
fxcore_fxcored_home: /home/fxcore/.fxcore

# List of base Python 2 packages to install via APT.
python__base_packages2:
  - python-httplib2
  - python-pycurl
  - python-setuptools

# Python management.
python__enabled: true

# List of Python 2 packages to install via PIP.
docker_server__default_pip_packages:
  - name: 'docker'

# List of Python 3 packages to install via PIP.
docker_server__default_pip3_packages:
  - docker
  - docker-compose
  - jmespath

docker_server__dns_nameserver: ''
docker_server__dns_search: ''

docker_server__python__dependent_packages2:
  - python-setuptools
  - python-dev

# Enable support for Python 3 management.
python__v3: true

# Lists of FQDN hostnames which should be added to systemwide.
sshd__known_hosts:
  - github.com

# Manage unattended package upgrades.
unattended_upgrades__enabled: true

# Manage the kernel configuration.
sysctl__enabled: false

# List of UNIX system user accounts to manage.
system_users__accounts:

  - name: ansible
    admin: true
    groups:
      - sudo
    sshkeys:
      - 'ssh-ed25519 {{ ansible_ssh_key }}'

# Manage different UNIX groups.
users__groups:

  - name: sudo
    user: False

# List of base APT packages to install.
users__base_packages:
  - acl
  - libuser

# List of base APT packages to install.
system_users__base_packages: '{{ users__base_packages }}'

# Ansible manage system user accounts.
system_users__enabled: true
