---
# Manage Advanced Package Manager configuration.
apt__enabled: True

docker_server__python__dependent_packages3:
  - python3-dev
  - python3-docker
  - python3-setuptools
  - python3-virtualenv

# Install the upstream version of Docker.
docker_server__upstream: True

# List of fxcored keys.
fxcore_fxcored_keys: []

# Home path for config and data.
fxcore_fxcored_home: /home/fxcore/.fxcore

# List of base Python 2 packages to install via APT.
python__base_packages2:
  - python-httplib2
  - python-pycurl
  - python-setuptools

# Python management.
python__enabled: True

# List of Python 3 packages to install via PIP.
docker_server__default_pip3_packages:
  - docker
  - docker-compose
  - jmespath

docker_server__dns_nameserver: ''
docker_server__dns_search: ''

docker_server__python__dependent_packages2:
  - python-setuptools
  - python-dev

# Enable support for Python 3 management.
python__v3: True

# Lists of FQDN hostnames which should be added to systemwide.
sshd__known_hosts:
  - github.com

# Manage unattended package upgrades.
unattended_upgrades__enabled: True

# Manage the kernel configuration.
sysctl__enabled: False

# List of UNIX system user accounts to manage.
system_users__accounts:

  - name: ansible
    # sshkeys:
    #   - ssh-ed25519 ...

# List of base APT packages to install.
system_users__base_packages:
  - acl
  - libuser

# Ansible manage system user accounts.
system_users__enabled: True
