---
# Manage Advanced Package Manager configuration.
apt__enabled: True

# Install the upstream version of Docker.
docker_server__upstream: True

# Lists of FQDN hostnames which should be added to systemwide.
sshd__known_hosts:
  - github.com

# Manage unattended package upgrades.
unattended_upgrades__enabled: True

# Enables debops.users to manage user accounts.
users__enabled: True
