---
- name: Manage Docker configuration
  collections:
    - debops.debops

  hosts: fxcore
  become: true

  roles:

    - role: apt
      tags:
        - role::apt
        - skip::apt
      vars:
        apt__packages: []

    - role: apt
      tags:
        - role::apt
        - skip::apt
