---
- name: Manage SSHD configuration
  become: true
  collections:
    - debops.debops

  hosts: fxcore

  pre_tasks:

    - name: Prepare sshd environment
      import_role:
        name: sshd
        tasks_from: main_env
      tags:
        - role::sshd

  roles:

    - role: sshd
      tags:
        - role::sshd
        - skip::sshd
