---
- name: Unattended upgrades
  become: true
  collections:
    - debops.debops

  hosts: fxcore

  pre_tasks:

  roles:

    - role: unattended_upgrades
      tags:
        - role::unattended_upgrades
        - skip::unattended_upgrades
