---
- name: Manage kernel modules
  become: true
  collections:
    - debops.debops
    - debops.roles01

  hosts: all

  pre_tasks:

  roles:

    - role: kmod
      tags:
        - role::kmod
        - skip::kmod
