---
- name: Manage Docker configuration
  collections:
    - debops.debops

  hosts: all
  become: true

  roles:

    - role: sysctl
      tags:
        - role::docker_server
        - skip::docker_server
