---
- name: Manage node setup
  collections:
    - debops.debops

  hosts: fxcore
  become: true
  become_flags: -i

  tasks:
    - name: Admin tasks
      block:
        - name: Volume directories
          file:
            path: '{{ fxcore_docker_volume_path ~ "/" ~ item }}'
            state: directory
            mode: u=rwx,g=rwx,o=
          loop: '{{ fxcore_docker_volume_names }}'

    - name: User tasks
      become_user: fxcore
      block:
        - ansible.builtin.git:
            dest: fx-core-docker
            force: true
            repo: https://github.com/cogni-fx/fx-core-docker.git
            version: main
          become_user: fxcore
          name: Git repo
          register: git_res

        - name: Docker volumes
          community.docker.docker_volume:
            name: '{{ item }}'
            driver_options:
              device: '{{ fxcore_docker_volume_path ~ "/" ~ item }}'
              o: bind
              type: none
          loop: '{{ fxcore_docker_volume_names }}'

        - name: Docker Compose
          community.docker.docker_compose:
            build: "{{ git_res.changed }}"
            project_src: fx-core-docker/{{ fxcore_network }}
            #pull: "{{ git_res.changed }}"
            remove_orphans: "{{ git_res.changed }}"
            restarted: "{{ git_res.changed }}"
          register: output
          when: not ansible_check_mode
