---
- name: Manage Docker configuration
  collections:
    - debops.debops

  hosts:
    - fxcore
    - fxcore_mainnet
  become: True

  roles:

    - role: apt
      tags:
        - role::apt
        - skip::apt
