---
- name: Manage Docker configuration
  collections:
    - debops.debops
    - debops.roles01

  hosts:
    - fxcore_testnet
  become: True

  roles:

    - role: python
      tags:
        - role::docker_server
        - role::python
        - skip::python

    - role: docker_server
      tags:
        - role::docker_server
        - skip::docker_server
