---
- name: Manage local users and groups
  collections:
    - debops.debops

  hosts: fxcore_testnet
  become: True

  roles:

    - role: system_users
      tags:
        - role::system_users
        - skip::system_users
